import type { InboxMessage, Lead, Template } from "@/lib/types/database";

export const inboxLeads: Lead[] = [
  {
    id: "il1", first_name: "Marie", last_name: "Laurent", email: "m.laurent@techcorp.fr",
    phone: "+33 6 12 34 56 78", company: "TechCorp", lead_type: "b2b", source: "linkedin",
    pipeline_stage_id: "b2b-3", assigned_to: null, score: 85, nb_properties: 45,
    status: "active", notes: null, metadata: {}, created_at: "2026-02-10T10:00:00Z", updated_at: "2026-02-18T14:30:00Z",
  },
  {
    id: "il2", first_name: "Claire", last_name: "Dubois", email: "c.dubois@cloudnative.fr",
    phone: "+33 6 45 67 89 01", company: "CloudNative", lead_type: "b2b", source: "seo",
    pipeline_stage_id: "b2b-1", assigned_to: null, score: 40, nb_properties: 5,
    status: "active", notes: null, metadata: {}, created_at: "2026-02-15T11:00:00Z", updated_at: "2026-02-15T11:00:00Z",
  },
  {
    id: "il3", first_name: "Thomas", last_name: "Leroy", email: "t.leroy@finops.tech",
    phone: "+33 6 56 78 90 12", company: "FinOps Tech", lead_type: "b2b", source: "webinar",
    pipeline_stage_id: "b2b-3", assigned_to: null, score: 78, nb_properties: 32,
    status: "active", notes: null, metadata: {}, created_at: "2026-02-08T14:00:00Z", updated_at: "2026-02-18T09:00:00Z",
  },
  {
    id: "il4", first_name: "Lucas", last_name: "Moreau", email: "l.moreau@datascale.com",
    phone: "+33 6 34 56 78 90", company: "DataScale", lead_type: "b2b", source: "partenaire",
    pipeline_stage_id: "b2b-4", assigned_to: null, score: 91, nb_properties: 120,
    status: "active", notes: null, metadata: {}, created_at: "2026-02-05T09:00:00Z", updated_at: "2026-02-19T10:00:00Z",
  },
  {
    id: "il5", first_name: "Antoine", last_name: "Rousseau", email: "a.rousseau@devtools.io",
    phone: "+33 6 67 89 01 23", company: "DevTools.io", lead_type: "b2b", source: "linkedin",
    pipeline_stage_id: "b2b-2", assigned_to: null, score: 65, nb_properties: 15,
    status: "active", notes: null, metadata: {}, created_at: "2026-02-11T10:00:00Z", updated_at: "2026-02-16T15:00:00Z",
  },
  {
    id: "il6", first_name: "Sophie", last_name: "Bernard", email: "s.bernard@gmail.com",
    phone: "+33 6 90 12 34 56", company: null, lead_type: "b2c", source: "formulaire",
    pipeline_stage_id: "b2c-2", assigned_to: null, score: 45, nb_properties: 2,
    status: "active", notes: null, metadata: {}, created_at: "2026-02-13T09:00:00Z", updated_at: "2026-02-18T10:00:00Z",
  },
  {
    id: "il7", first_name: "Jean-Marc", last_name: "Petit", email: "jm.petit@orange.fr",
    phone: "+33 6 11 22 33 44", company: null, lead_type: "b2c", source: "seo",
    pipeline_stage_id: "b2c-1", assigned_to: null, score: 30, nb_properties: 1,
    status: "active", notes: null, metadata: {}, created_at: "2026-02-17T08:00:00Z", updated_at: "2026-02-17T08:00:00Z",
  },
  {
    id: "il8", first_name: "Nathalie", last_name: "Girard", email: "n.girard@hotmail.fr",
    phone: "+33 6 55 66 77 88", company: null, lead_type: "b2c", source: "formulaire",
    pipeline_stage_id: "b2c-3", assigned_to: null, score: 60, nb_properties: 2,
    status: "active", notes: null, metadata: {}, created_at: "2026-02-06T15:00:00Z", updated_at: "2026-02-18T17:00:00Z",
  },
  {
    id: "il9", first_name: "Olivier", last_name: "Fabre", email: "o.fabre@conciergerie-azur.fr",
    phone: "+33 6 99 88 77 66", company: "Conciergerie Azur", lead_type: "b2b", source: "salon",
    pipeline_stage_id: "b2b-2", assigned_to: null, score: 72, nb_properties: 65,
    status: "active", notes: null, metadata: {}, created_at: "2026-02-12T11:00:00Z", updated_at: "2026-02-18T12:00:00Z",
  },
];

export const inboxMessages: InboxMessage[] = [
  {
    id: "m1",
    lead_id: "il1",
    direction: "inbound",
    channel: "email",
    subject: "RE: Proposition commerciale TechCorp",
    content: "Bonjour,\n\nNous avons etudie votre proposition avec attention. Quelques questions :\n\n1. Quels sont les paliers de pricing au-dela de 50k calls/mois ?\n2. Y a-t-il une remise pour un engagement annuel ?\n3. Pouvez-vous preciser les SLA inclus dans le plan Pro+ ?\n\nNotre CFO souhaite egalement recevoir une copie de votre DPA pour validation par notre equipe juridique.\n\nMerci de votre retour rapide, nous aimerions finaliser avant la fin du mois.\n\nCordialement,\nMarie Laurent\nHead of Sales - TechCorp",
    status: "unread",
    assigned_to: null,
    template_id: null,
    created_at: "2026-02-19T08:30:00Z",
  },
  {
    id: "m2",
    lead_id: "il2",
    direction: "inbound",
    channel: "form",
    subject: "Demande d'information - CloudNative",
    content: "Bonjour,\n\nNous sommes une startup de 5 personnes specialisee dans le cloud-native. Nous cherchons un outil pour automatiser notre process de vente SaaS, notamment :\n- Provisioning automatique des PoC\n- Generation de devis usage-based\n- Suivi des trials\n\nPouvez-vous nous proposer une demo ?\n\nClaire Dubois\nCEO - CloudNative",
    status: "unread",
    assigned_to: null,
    template_id: null,
    created_at: "2026-02-19T06:15:00Z",
  },
  {
    id: "m3",
    lead_id: "il3",
    direction: "inbound",
    channel: "email",
    subject: "Suite demo - Questions techniques securite",
    content: "Bonjour,\n\nSuite a notre demo de mardi, notre CTO et notre DPO ont quelques questions :\n\n1. Ou sont hebergees les donnees ? (exigence UE)\n2. Avez-vous une certification SOC2 ou ISO 27001 ?\n3. Pouvez-vous nous envoyer votre DPA standard ?\n4. Quel est le processus de suppression des donnees en fin de contrat ?\n\nCes elements sont necessaires pour la validation par notre comite securite.\n\nThomas Leroy\nHead of Sales - FinOps Tech",
    status: "in_progress",
    assigned_to: null,
    template_id: null,
    created_at: "2026-02-18T16:45:00Z",
  },
  {
    id: "m4",
    lead_id: "il4",
    direction: "outbound",
    channel: "email",
    subject: "Relance proposition DataScale",
    content: "Bonjour Lucas,\n\nJe me permets de vous relancer concernant la proposition commerciale envoyee la semaine derniere.\n\nAvez-vous eu le temps de la parcourir avec votre CFO ? Je reste disponible pour en discuter par telephone ou visio si vous avez des questions.\n\nCordialement,\nJean Dupont\nCommercial - CheckEasy",
    status: "done",
    assigned_to: null,
    template_id: null,
    created_at: "2026-02-18T10:00:00Z",
  },
  {
    id: "m5",
    lead_id: "il5",
    direction: "inbound",
    channel: "linkedin",
    subject: "Message LinkedIn - DevTools.io",
    content: "Salut,\n\nJe suis CTO chez DevTools.io. J'ai vu votre post sur la reduction des cycles de vente SaaS et ca m'interesse beaucoup.\n\nNotre equipe commerciale perd un temps fou a creer des PoC manuellement et a calculer les devis usage-based. Votre solution semble repondre exactement a nos besoins.\n\nOn peut planifier un call cette semaine ?\n\nAntoine Rousseau\nCTO - DevTools.io",
    status: "unread",
    assigned_to: null,
    template_id: null,
    created_at: "2026-02-18T14:20:00Z",
  },
  {
    id: "m6",
    lead_id: "il6",
    direction: "inbound",
    channel: "form",
    subject: "Question sur l'essai gratuit",
    content: "Bonjour,\n\nJ'ai commence l'essai gratuit il y a quelques jours et j'ai une question : est-il possible de connecter mon calendrier Airbnb pour automatiser les inspections apres chaque depart ?\n\nMerci,\nSophie Bernard",
    status: "unread",
    assigned_to: null,
    template_id: null,
    created_at: "2026-02-19T07:00:00Z",
  },
  {
    id: "m7",
    lead_id: "il1",
    direction: "outbound",
    channel: "email",
    subject: "Proposition commerciale TechCorp - Plan Pro+",
    content: "Bonjour Marie,\n\nSuite a notre demo, je vous adresse ci-joint notre proposition commerciale pour TechCorp.\n\nPlan recommande : Pro+ (45 biens)\nTarif : 199 EUR/mois\nEngagement : mensuel sans minimum\n\nInclus : onboarding personnalise + formation equipe.\n\nCordialement,\nJean Dupont",
    status: "done",
    assigned_to: null,
    template_id: null,
    created_at: "2026-02-16T11:00:00Z",
  },
  {
    id: "m8",
    lead_id: "il7",
    direction: "inbound",
    channel: "phone",
    subject: "Appel entrant - Probleme degradation",
    content: "Appel recu de Jean-Marc Petit (proprietaire, 1 bien a Chamonix).\n\nContexte : Son dernier voyageur a cause des degats dans la salle de bain (joint de douche arrache, miroir fele). Il n'a aucune preuve photo datee de l'etat avant l'arrivee.\n\nAirbnb refuse de le rembourser sans preuves. Il cherche une solution pour eviter que ca se reproduise.\n\nA rappeler demain matin.",
    status: "in_progress",
    assigned_to: null,
    template_id: null,
    created_at: "2026-02-17T17:30:00Z",
  },
  {
    id: "m9",
    lead_id: "il8",
    direction: "inbound",
    channel: "email",
    subject: "Retour apres 1 mois d'utilisation",
    content: "Bonjour,\n\nJe voulais vous faire un retour apres un mois d'utilisation de CheckEasy sur mes 2 biens en Bretagne.\n\nPoints positifs :\n- Les rapports IA sont tres precis\n- La detection d'anomalies m'a sauve 2 fois (tache sur canape, vitre felee)\n- L'interface est simple a utiliser\n\nPoints d'amelioration :\n- J'aimerais pouvoir exporter les rapports en PDF depuis l'app mobile\n- Le temps de chargement des photos est parfois long\n\nGlobalement je suis tres satisfaite et je recommande autour de moi.\n\nNathalie Girard",
    status: "done",
    assigned_to: null,
    template_id: null,
    created_at: "2026-02-18T09:15:00Z",
  },
  {
    id: "m10",
    lead_id: "il9",
    direction: "inbound",
    channel: "linkedin",
    subject: "Rencontre au salon Rent - Conciergerie Azur",
    content: "Bonjour,\n\nOn s'est croises au salon Rent la semaine derniere. Vous m'avez parle de CheckEasy pour automatiser les etats des lieux.\n\nJe gere 65 biens entre Nice et Cannes avec une equipe de 8 agents terrain. Notre process actuel est 100% papier + photos WhatsApp et c'est ingerable.\n\nJe suis tres interesse par une demo. Est-ce qu'on peut se voir la semaine prochaine ?\n\nOlivier Fabre\nGerant - Conciergerie Azur",
    status: "unread",
    assigned_to: null,
    template_id: null,
    created_at: "2026-02-18T11:00:00Z",
  },
  {
    id: "m11",
    lead_id: "il4",
    direction: "inbound",
    channel: "email",
    subject: "RE: Relance proposition DataScale",
    content: "Bonjour Jean,\n\nMerci pour votre relance. Notre CFO a valide le budget. Nous aimerions demarrer avec un pilote sur 30 biens d'abord, puis etendre a nos 120 biens si les resultats sont concluants.\n\nPouvez-vous nous envoyer une proposition ajustee pour cette approche par phases ?\n\nCordialement,\nLucas Moreau\nDirecteur General - DataScale",
    status: "unread",
    assigned_to: null,
    template_id: null,
    created_at: "2026-02-19T09:45:00Z",
  },
  {
    id: "m12",
    lead_id: "il6",
    direction: "outbound",
    channel: "email",
    subject: "RE: Question sur l'essai gratuit",
    content: "Bonjour Sophie,\n\nOui, la synchronisation avec le calendrier Airbnb est disponible ! Voici comment l'activer :\n\n1. Allez dans Parametres > Integrations\n2. Cliquez sur \"Connecter Airbnb\"\n3. Importez votre lien iCal\n\nLes inspections seront automatiquement planifiees apres chaque depart.\n\nN'hesitez pas si vous avez d'autres questions.\n\nL'equipe CheckEasy",
    status: "done",
    assigned_to: null,
    template_id: null,
    created_at: "2026-02-19T08:00:00Z",
  },
];

export const responseTemplates: Template[] = [
  // B2B Templates
  {
    id: "t1", name: "Premier contact conciergerie", template_type: "b2b", category: "prospection",
    subject: "{{entreprise}} - une question sur votre controle qualite",
    body: "Bonjour {{prenom}},\n\nJe me permets de vous contacter car je travaille avec plusieurs conciergeries en France sur un sujet qui revient constamment : la gestion du controle qualite menage et des etats des lieux.\n\nChez {{entreprise}}, avec {{nb_biens}} biens a gerer, vous avez probablement deja rencontre ce type de situations :\n- Un proprietaire qui signale une degradation que votre equipe n'a pas documentee\n- Un litige voyageur sans preuves photos horodatees\n- Des agents terrain dont vous ne pouvez pas verifier la qualite du travail a distance\n\nCheckEasy automatise tout ca avec l'IA. +2 000 biens equipes dans 3 pays.\n\nEst-ce que vous auriez 20 minutes cette semaine pour que je vous montre ?\n\nCordialement,\n{{commercial_prenom}}",
    variables: ["prenom", "entreprise", "nb_biens", "commercial_prenom"],
    created_by: null, created_at: "", updated_at: "",
  },
  {
    id: "t2", name: "Invitation demo personnalisee", template_type: "b2b", category: "demo",
    subject: "Demo CheckEasy pour {{entreprise}} - {{date_demo}}",
    body: "Bonjour {{prenom}},\n\nSuite a notre echange, je vous confirme votre demo personnalisee CheckEasy :\n\nDate : {{date_demo}}\nDuree : 25 minutes\n\nCe qu'on va vous montrer :\n1. Une inspection en live\n2. Le rapport IA genere en temps reel\n3. Le dashboard de suivi de votre parc de {{nb_biens}} biens\n4. Le calcul de ROI personnalise pour {{entreprise}}\n\n{{commercial_prenom}}\nCheckEasy",
    variables: ["prenom", "entreprise", "nb_biens", "date_demo", "commercial_prenom"],
    created_by: null, created_at: "", updated_at: "",
  },
  {
    id: "t3", name: "Suivi post-demo", template_type: "b2b", category: "suivi",
    subject: "Recap demo CheckEasy - {{entreprise}}",
    body: "Bonjour {{prenom}},\n\nMerci pour votre temps lors de la demo. Voici un recapitulatif :\n\nCe que CheckEasy apporte a {{entreprise}} :\n- Inspection IA en 5 min par bien (vs 20-30 min manuellement)\n- Rapports automatiques avec preuves horodatees a valeur juridique\n- Dashboard de suivi qualite pour vos {{nb_biens}} biens\n- Notifications temps reel aux proprietaires\n\nROI estime : ~{{nb_biens}} x 20 min/semaine economisees.\n\nProchaine etape : proposition commerciale sous 48h.\n\n{{commercial_prenom}}\nCheckEasy",
    variables: ["prenom", "entreprise", "nb_biens", "commercial_prenom"],
    created_by: null, created_at: "", updated_at: "",
  },
  {
    id: "t4", name: "Envoi proposition commerciale", template_type: "b2b", category: "closing",
    subject: "Proposition commerciale CheckEasy x {{entreprise}}",
    body: "Bonjour {{prenom}},\n\nComme convenu, voici la proposition commerciale pour {{entreprise}}.\n\nPlan recommande : {{plan}}\nNombre de biens couverts : {{nb_biens}}\nEngagement : mensuel, sans engagement minimum\nInclus : onboarding personnalise + formation equipe terrain\n\nOffre de lancement : 1 mois offert sur votre premiere souscription.\n\nLa proposition est valable 15 jours.\n\n{{commercial_prenom}}\nCheckEasy",
    variables: ["prenom", "entreprise", "nb_biens", "plan", "commercial_prenom"],
    created_by: null, created_at: "", updated_at: "",
  },
  {
    id: "t5", name: "Relance signature", template_type: "b2b", category: "relance",
    subject: "{{prenom}}, votre proposition CheckEasy expire bientot",
    body: "Bonjour {{prenom}},\n\nJe reviens vers vous concernant la proposition commerciale envoyee la semaine derniere pour {{entreprise}}.\n\nSi vous avez des questions ou des points a clarifier, je suis disponible par telephone ou visio.\n\nLa proposition avec le mois offert est valable encore 8 jours.\n\n{{commercial_prenom}}\nCheckEasy",
    variables: ["prenom", "entreprise", "commercial_prenom"],
    created_by: null, created_at: "", updated_at: "",
  },
  // B2C Templates
  {
    id: "t6", name: "Bienvenue essai B2C", template_type: "b2c", category: "onboarding",
    subject: "Bienvenue {{prenom}} ! Votre essai CheckEasy est actif",
    body: "Bonjour {{prenom}},\n\nBienvenue sur CheckEasy ! Votre essai gratuit de 14 jours est maintenant actif.\n\nVoici comment demarrer en 3 minutes :\n1. Ajoutez votre premier bien (adresse + photos de reference)\n2. Lancez votre premiere inspection guidee\n3. Recevez votre rapport IA automatique\n\nUne question ? Repondez simplement a cet email, on vous repond en moins de 2h.\n\nL'equipe CheckEasy",
    variables: ["prenom"],
    created_by: null, created_at: "", updated_at: "",
  },
  {
    id: "t7", name: "Relance activation J+3", template_type: "b2c", category: "relance",
    subject: "{{prenom}}, votre bien n'est pas encore protege",
    body: "Bonjour {{prenom}},\n\nVous avez cree votre compte CheckEasy il y a 3 jours, mais vous n'avez pas encore lance votre premiere inspection.\n\nCa prend litteralement 5 minutes.\n\nSaviez-vous que 73% des litiges Airbnb auraient pu etre evites avec un etat des lieux photo horodate ?\n\nNe laissez pas votre bien sans protection. Votre essai se termine dans 11 jours.\n\nL'equipe CheckEasy",
    variables: ["prenom"],
    created_by: null, created_at: "", updated_at: "",
  },
  {
    id: "t8", name: "Felicitations premiere inspection", template_type: "b2c", category: "engagement",
    subject: "Bravo {{prenom}} ! Votre premier rapport IA est pret",
    body: "Bonjour {{prenom}},\n\nVotre premier rapport d'inspection est pret ! Votre bien est maintenant documente avec des preuves photos horodatees et geolocalisees.\n\nCe que votre rapport contient :\n- Photos horodatees de chaque piece\n- Analyse IA de l'etat du logement\n- Detection automatique d'anomalies\n- Rapport PDF partageable (valeur juridique)\n\nImaginez : ce rapport existe maintenant pour CHAQUE rotation de voyageur, automatiquement.\n\nL'equipe CheckEasy",
    variables: ["prenom"],
    created_by: null, created_at: "", updated_at: "",
  },
  {
    id: "t9", name: "Proposition upgrade", template_type: "b2c", category: "upsell",
    subject: "{{prenom}}, passez au niveau superieur",
    body: "Bonjour {{prenom}},\n\nVous utilisez CheckEasy regulierement et c'est exactement pour ca qu'on l'a cree.\n\nVoici ce que vous debloquez en passant au niveau superieur :\n\nPlan Essentiel (4.99 EUR/mois) :\n- Rapports illimites\n- Historique complet 12 mois\n- Export PDF haute qualite\n- Notifications temps reel\n\nPlan Intensif (19.99 EUR/mois) :\n- Tout le plan Essentiel\n- Planning agents de menage\n- Livret d'accueil IA\n- Sync calendrier Airbnb/Booking/Abritel\n- Support prioritaire\n\nPour le prix d'un cafe par jour, votre bien est protege 24/7.\n\nL'equipe CheckEasy",
    variables: ["prenom"],
    created_by: null, created_at: "", updated_at: "",
  },
  {
    id: "t10", name: "Support / aide B2C", template_type: "b2c", category: "support",
    subject: "{{prenom}}, on peut vous aider ?",
    body: "Bonjour {{prenom}},\n\nOn a remarque que vous n'avez pas utilise CheckEasy recemment. Tout va bien ?\n\nSi vous rencontrez une difficulte, on est la pour vous aider :\n- Repondez a cet email - reponse en moins de 2h\n- Consultez notre centre d'aide\n\nVotre avis compte. Si quelque chose ne vous convient pas, dites-le nous.\n\nL'equipe CheckEasy",
    variables: ["prenom"],
    created_by: null, created_at: "", updated_at: "",
  },
];

// Helper to attach leads to messages
export function getMessagesWithLeads(): (InboxMessage & { lead?: Lead })[] {
  return inboxMessages.map((msg) => ({
    ...msg,
    lead: inboxLeads.find((l) => l.id === msg.lead_id),
  }));
}
